# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-10 17:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_auto_20170710_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('justification', models.CharField(max_length=1000)),
                ('neg_impact', models.CharField(max_length=1000)),
                ('request_date', models.DateField()),
                ('work_date', models.DateField()),
                ('internal_auth', models.BooleanField(default=False)),
                ('customer_auth', models.BooleanField(default=False)),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engineer', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to=settings.AUTH_USER_MODEL)),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Infra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Location')),
            ],
        ),
        migrations.CreateModel(
            name='InfraType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='infra',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.OS'),
        ),
        migrations.AddField(
            model_name='infra',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.InfraType'),
        ),
    ]
