# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-11 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_infra_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='change',
            name='justification',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='change',
            name='neg_impact',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
