# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-11 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_auto_20170711_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
