# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-11 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_auto_20170711_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='change',
            name='request_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='change',
            name='work_date',
            field=models.DateField(null=True),
        ),
    ]
