# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-15 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_auto_20170711_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
