# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-15 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_change_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
