# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-16 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_auto_20170714_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='quote',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
