# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-16 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_change_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
