# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-17 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_change_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='denial_exp',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
