# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-17 00:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0012_change_denial_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='customer_auth_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_auth', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='change',
            name='internal_auth_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_auth', to=settings.AUTH_USER_MODEL),
        ),
    ]
