# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-17 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0016_auto_20170717_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change',
            old_name='denial_exp',
            new_name='customer_deny_exp',
        ),
        migrations.AddField(
            model_name='change',
            name='internal_deny_exp',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
