# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-06 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170705_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='locations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Location'),
        ),
    ]
