# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-10 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170706_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='locations',
        ),
        migrations.AddField(
            model_name='location',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Company'),
        ),
    ]
