# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-25 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170710_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reg_admin',
            field=models.BooleanField(default=False),
        ),
    ]
