# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-27 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_user_reg_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='super_admin',
            field=models.BooleanField(default=False),
        ),
    ]
